version: "3.9"
services:
  app:
    image: node:14
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: mantle
      MYSQL_PASSWORD: joon67346jih
      MYSQL_DB: mantle_product

  mysql:
    image: mysql/mysql-server
    volumes:
      - product-mysql-data:/var/lib/mysql
      - ./db/data/mantle_product.sql:/docker-entrypoint-initdb.d/mantle_product.sql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: mantle
      MYSQL_PASSWORD: joon67346jih
      MYSQL_DATABASE: mantle_product

volumes:
  product-mysql-data:
